from pydantic import BaseModel, Field, validator
from typing import Optional
from enum import Enum
from app.core.messaging.models import MessageChannel


class EOtpPurpose(str, Enum):
    LOGIN = "LOGIN"
    RESET_PASSWORD = "RESET_PASSWORD"
    SENSITIVE_ACTION = "SENSITIVE_ACTION"
    ONBOARDING = "ONBOARDING"


class OTPRequest(BaseModel):
    destination: str = Field(
        ...,
        description="Recipient — email address or phone number depending on the channel.",
        examples=["user@example.com", "+521234567890"],
    )
    code: str = Field(
        ...,
        min_length=4,
        max_length=8,
        description="OTP code to dispatch (plaintext, not the hash). Generated by the calling service.",
        examples=["A1B2C3"],
    )
    purpose: EOtpPurpose = Field(
        default=EOtpPurpose.LOGIN,
        description="Purpose of the OTP — drives the email subject and template context.",
        examples=["LOGIN"],
    )
    expiry_minutes: Optional[int] = Field(
        None,
        ge=0,
        le=1440,
        description="Code expiration time in minutes.",
        examples=[10],
    )
    redirect_url: Optional[str] = Field(
        None,
        max_length=2048,
        description="Optional redirect URL shown as a CTA button in the email.",
        examples=["https://app.com/verify"],
    )
    channel: MessageChannel = Field(
        default=MessageChannel.EMAIL,
        description="Delivery channel: email, sms, or whatsapp.",
        examples=["email"],
    )

    @validator("redirect_url")
    def validate_redirect_url(cls, v):
        if v is not None and v.strip():
            if not (v.startswith("http://") or v.startswith("https://")):
                raise ValueError("Redirect URL must start with http:// or https://")
        return v


class WelcomeRequest(BaseModel):
    """Sent when an applicant is approved by admin and becomes an active user."""
    email: str = Field(..., description="Recipient email address.", examples=["juan@example.com"])
    user_name: str = Field(..., description="Name of the user for personalization.", examples=["Juan Pérez"])
    login_url: Optional[str] = Field(None, description="Direct login link shown as CTA button.", examples=["https://app.com/login"])
    channel: MessageChannel = Field(default=MessageChannel.EMAIL, description="Delivery channel.")


class OTPResponse(BaseModel):
    success: bool = Field(..., description="True if the message was dispatched successfully.")
    message: str = Field(..., description="Human-readable outcome message.")
    sent_to: str = Field(..., description="Destination the message was sent to.")
    timestamp: str = Field(..., description="ISO 8601 UTC timestamp of dispatch.")
    expiry_minutes: Optional[int] = Field(None, description="Applied expiration time in minutes.")
    has_action_button: bool = Field(False, description="Whether a CTA button was included.")
    logo_used: Optional[str] = Field(None, description="Branding logo URL used in the template.")
